name: Docker build & push

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      
jobs:
  build-push-ecr-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Define branch/tag sources
        id: sources
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}
          IMAGE_TAG: ${{ steps.sources.outputs.SOURCE_TAG }}
        run: |
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

          #docker build -t 006563289334.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:latest .
          #docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          #docker push 006563289334.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:latest
